---
name: DevOps With Testing and Production

on:
  push:
    branches: 
    - "main"
    - "testing" 
    - "second-test"

  pull_request:
    branches:
    - "main"
    - "testing" 

  
  workflow_dispatch:


jobs:

  deploy-to-aws:
    name: Copy files to AWS EC2 Testing
    runs-on: ubuntu-22.04
    
    #needs: [gitleaks,copy_paste_detector,phpstan,php_lint]
    environment: 
      name: test
      url: http://deploy-ec2-test.duckdns.org/
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST_DNS_PRODUCTION }}
        username: ${{ secrets.USERNAME_PRODUCTION }}
        key: ${{ secrets.EC2_SSH_KEY_PRODUCTION }}
        port: 22
        script: cd /var/www/html/ && rm -r * && git clone -b testing https://github.com/franco-lamas/deploy-ec2



  deploy-to-prod:
    name: Copy files to AWS EC2 Testing
    runs-on: ubuntu-22.04
    #needs: [gitleaks,copy_paste_detector,phpstan,php_lint]
    environment: 
      name: prod
      url: http://deploy-ec2-test.duckdns.org/
    steps:
    - name: Checkout the files
      uses: actions/checkout@v2
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: src
        remote: ${{ secrets.TARGET_DIR_PRODUCTION }} 
        host: ${{ secrets.HOST_DNS_PRODUCTION }}
        username: ${{ secrets.USERNAME_PRODUCTION }}

        privateKey: ${{ secrets.EC2_SSH_KEY_PRODUCTION }}
        rmRemote: true

