---
name: DevOps With Testing and Production

on:
  push:
    branches: 
    - "main"
    - "testing" 

  pull_request:
    branches:
    - "main"
    - "testing" 

  
  workflow_dispatch:


jobs:

# Extracted from https://github.com/gastonbarbaccia/devops_v1/
  gitleaks:
      name: Gitleaks
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: gastonbarbaccia/gitleaks@v2.1
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        - name: Get the output from the gitleaks step
          run: |
            echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
            echo "result: ${{ steps.gitleaks.outputs.result }}"
            echo "output: ${{ steps.gitleaks.outputs.output }}"
            echo "command: ${{ steps.gitleaks.outputs.command }}"
            echo "report: ${{ steps.gitleaks.outputs.report }}"
        - name: Upload SARIF report
          if: steps.gitleaks.outputs.exitcode == 1
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: ${{ steps.gitleaks.outputs.report }} 

  copy_paste_detector:
    name: Copy Paste Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP Copy Paste Detector
        uses: StephaneBour/actions-php-cpd@1.0
        with:
          dir: "src/"

  phpstan:
    name: PHP Stan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/phpstan@v3
        with:
          path: "src/"
          memory_limit: 256M

  php_lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.4
        with:
          dir: "src/"

# ------End of extracted Code-------

  deploy-to-aws:
    name: Copy files to AWS EC2 Testing
    runs-on: ubuntu-22.04
    needs: [gitleaks,copy_paste_detector,phpstan,php_lint]
    environment: 
      name: test
      url: http://deploy-ec2-test.duckdns.org/
    continue-on-error:  ${{ secrets.CONTINUE_ERROR_TEST }}
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST_DNS_PRODUCTION }}
        username: ${{ secrets.USERNAME_PRODUCTION }}
        key: ${{ secrets.EC2_SSH_KEY_PRODUCTION }}
        port: 22
        script: |
          cd /var/www/html/ && rm -r *
          git clone -b testing https://github.com/franco-lamas/deploy-ec2 
          mv -v /var/www/html/deploy-ec2/src/* /var/www/html/ 
          rm -rf deploy-ec2


  deploy-to-Prod:
    name: Copy files to AWS EC2 Prod
    runs-on: ubuntu-22.04
    needs: [gitleaks,copy_paste_detector,phpstan,php_lint]
    environment: 
      name: prod
      url: http://deploy-ec2-prod.duckdns.org/
    continue-on-error: ${{ secrets.CONTINUE_ERROR_PROD }}
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST_DNS_PRODUCTION }}
        username: ${{ secrets.USERNAME_PRODUCTION }}
        key: ${{ secrets.EC2_SSH_KEY_PRODUCTION }}
        port: 22
        script: |
          cd /var/www/html/ && rm -r *
          git clone https://github.com/franco-lamas/deploy-ec2 
          mv -v /var/www/html/deploy-ec2/src/* /var/www/html/ 
          rm -rf deploy-ec2

